# Generated by Django 5.2.17 on 2026-09-07 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, max_length=110, verbose_name='Slug')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom de la boutique')),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True, verbose_name='Slug')),
                ('tagline', models.CharField(blank=True, max_length=200, verbose_name="Phrase d'accroche")),
                ('whatsapp_number', models.CharField(help_text='Format international sans le "+" ni espaces, ex: 33612345678.', max_length=20, verbose_name='Numéro WhatsApp')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='stores/', verbose_name='Logo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Boutique active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
            ],
            options={
                'verbose_name': 'Boutique',
                'verbose_name_plural': 'Boutiques',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom du produit')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ajouté le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.category', verbose_name='Catégorie')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.store', verbose_name='Boutique')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Photo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Photo produit',
                'verbose_name_plural': 'Photos produit',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='catalog.store', verbose_name='Boutique'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('store', 'slug')},
        ),
    ]
