# Generated by Django 5.2.17 on 2026-09-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='currency',
            field=models.CharField(default='€', help_text='Symbole ou code affiché à côté des prix, ex: €, FCFA, $.', max_length=10, verbose_name='Devise'),
        ),
    ]
