# Generated by Django 5.2.17 on 2026-09-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_store_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='accent_color',
            field=models.CharField(default='#e2a13a', help_text='Couleur des prix et éléments mis en avant, format hexadécimal (ex: #e2a13a).', max_length=7, verbose_name="Couleur d'accent"),
        ),
        migrations.AddField(
            model_name='store',
            name='primary_color',
            field=models.CharField(default='#2f4b3c', help_text="Couleur du bandeau d'en-tête, format hexadécimal (ex: #2f4b3c).", max_length=7, verbose_name='Couleur principale'),
        ),
    ]
