# Generated by Django 5.2.17 on 2026-09-16 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_store_accent_color_store_primary_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Demandé le')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='catalog.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Demande WhatsApp',
                'verbose_name_plural': 'Demandes WhatsApp',
                'ordering': ['-created_at'],
            },
        ),
    ]
