# Generated by Django 5.2.17 on 2026-09-17 22:18

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_productinquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/', validators=[catalog.models.validate_image_size], verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='store',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='stores/', validators=[catalog.models.validate_image_size], verbose_name='Logo'),
        ),
    ]
